Dev
HermanShpryhau/MJC-REST-Basics pull request #1
Opened 2021-10-05 06:47 UTC by HermanShpryhau

2021-10-09 06:30 UTC, HermanShpryhau commented
Finished

2021-10-09 06:31 UTC, HermanShpryhau commented
Finished

2021-10-11 20:18 UTC, natashlapakova requested changes
I cannot find requirment 13: Repository layer should be tested using integration tests with an in-memory embedded database (all operations with certificates).

2021-10-11 20:18 UTC, natashlapakova commented on web/src/main/java/com/epam/esm/web/controller/TagController.java
> +     * Gets tags associated with gift certificate.
misprint Gets gift certificates with tag

2021-10-11 20:18 UTC, natashlapakova commented on service/src/main/java/com/epam/esm/service/TagService.java
> +     * @return List of associated tags
* fetches gift certificates?

2021-10-11 20:18 UTC, natashlapakova commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    @Override
update certificates should be done in transaction

2021-10-11 20:18 UTC, natashlapakova commented on web/src/main/java/com/epam/esm/web/config/WebConfig.java
> +        LocalValidatorFactoryBean localValidatorFactoryBean = new LocalValidatorFactoryBean();
Why do you need this?

2021-10-11 20:19 UTC, natashlapakova commented on db/fill_db_script.py
> +import mysql.connector as mysql
Not sure that this code is needed here

2021-10-11 20:27 UTC, natashlapakova commented on service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +
I would prefer to use  @InjectMocks and @Mock here for simplicity and readability, but let's discuss

2021-10-11 20:47 UTC, gearok commented on web/src/main/java/com/epam/esm/web/controller/TagController.java
> +     * Gets tags associated with gift certificate.
Fixed

2021-10-11 20:47 UTC, gearok commented on service/src/main/java/com/epam/esm/service/TagService.java
> +     * @return List of associated tags
Fixed

2021-10-11 20:47 UTC, HermanShpryhau commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    @Override
Fixed

2021-10-11 22:02 UTC, gearok commented on web/src/main/java/com/epam/esm/web/config/WebConfig.java
> +        LocalValidatorFactoryBean localValidatorFactoryBean = new LocalValidatorFactoryBean();
Removed this bean

2021-10-11 22:02 UTC, HermanShpryhau commented on db/fill_db_script.py
> +import mysql.connector as mysql
Removed this script file from repo

2021-10-11 22:03 UTC, gearok commented
> I cannot find requirment 13: Repository layer should be tested using integration tests with an in-memory embedded database (all operations with certificates).

Added integration tests for `GiftCertificateRepository`

2021-10-12 13:14 UTC, gearok commented on service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +
I've rewritten all test with Mockito annotations

2021-10-15 15:22 UTC, gearok commented on service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +    }
I wonder if it's ok not to test this method with different combinations of arguments since it only passes them to a mocked object and the tested behavior isn't connected with them.

2021-10-16 07:24 UTC, natashlapakova commented on service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +    }
test should check only service logic, if parameters don't influence on the method execution, then you shouldn't check them.

2021-10-16 07:48 UTC, natashlapakova commented on persistence/src/main/java/com/epam/esm/persistence/repository/impl/GiftCertificatePreparedStatementCreator.java
> +    private static final String BASE_QUERY = "SELECT DISTINCT Gift_certificate.id, Gift_certificate.name, " +
distinct 👍

2021-10-16 07:52 UTC, natashlapakova commented on persistence/src/main/java/com/epam/esm/persistence/repository/impl/GiftCertificateRepositoryImpl.java
> +
javadoc

2021-10-16 07:53 UTC, natashlapakova commented on persistence/src/main/java/com/epam/esm/persistence/repository/impl/GiftCertificateRepositoryImpl.java
> +
javadoc on class

2021-10-16 07:55 UTC, natashlapakova commented on service/src/main/java/com/epam/esm/service/GiftCertificateService.java
> +
Javadoc on class

2021-10-20 08:09 UTC, natashlapakova approved these changes

2021-10-20 08:22 UTC, merged